apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argoapp
spec:
  destination:
    namespace: argoapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: manifests/helm-app
    repoURL: https://github.com/Vadakan/medium-argocd.git
    targetRevision: HEAD
  syncPolicy: {}
